# Generated by Django 4.2 on 2023-09-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'gallarytb',
            },
        ),
    ]
