# Generated by Django 4.2 on 2023-09-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='dob',
        ),
    ]
