# Generated by Django 4.2 on 2023-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_sign_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='Phone',
            field=models.CharField(max_length=55),
        ),
    ]
