# Generated by Django 4.2 on 2023-10-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_firstname_job_name_remove_job_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job',
        ),
    ]
