# Generated by Django 4.2 on 2023-10-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobmodel',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=254)),
                ('Resume', models.ImageField(upload_to='uploads/')),
                ('Pic', models.ImageField(upload_to='uploads/')),
                ('Password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'jobtb',
            },
        ),
    ]
