# Generated by Django 4.2 on 2023-10-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_jobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=55)),
                ('Message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contacttb',
            },
        ),
    ]
