# Generated by Django 4.2 on 2023-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_servicesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
